<?php

abstract class Constants {

    const CODIGO_BANCO_SANTANDER = "033"; //Antigamente era 353
    const TIPO_MOEDA = 'REAL';

    /* espécies de documentos(boletos) */
    const ESPECIE_DE_DOCUMENTO_ALUGUEL = 'Aluguel';
    const ESPECIE_DE_DOCUMENTO_APOLICE_DE_SEGURO = 'AS';
    const ESPECIE_DE_DOCUMENTO_Cheque = 'CH';
    const ESPECIE_DE_DOCUMENTO_CONTRATO = 'C';
    const ESPECIE_DE_DOCUMENTO_CONTRIBUICAO_CONFEDERATIVA = 'CC';
    const ESPECIE_DE_DOCUMENTO_CONTRIBUICAO_OU_SEGUROS = 'CS';
    const ESPECIE_DE_DOCUMENTO_DIVIDA_ATIVA_DO_ESTADO = 'DAE';
    const ESPECIE_DE_DOCUMENTO_DIVIDA_ATIVA_DO_MUNICIPIO = 'DAM';
    const ESPECIE_DE_DOCUMENTO_DIVIDA_ATIVA_DA_UNIAO = 'DAU';
    const ESPECIE_DE_DOCUMENTO_DUPLICATA_MERCANTIL_OU_INDICACAO = 'DMI';
    const ESPECIE_DE_DOCUMENTO_DUPLICATA_MERCANTIL = 'DM';
    const ESPECIE_DE_DOCUMENTO_DUPLICATA_RURAL = 'DR';
    const ESPECIE_DE_DOCUMENTO_DUPLICATA_DE_SERVICO = 'DS';
    const ESPECIE_DE_DOCUMENTO_DUPLICATA_DE_SERVICO_OU_INDICACAO = 'DSI';
    const ESPECIE_DE_DOCUMENTO_FATURA = 'F';
    const ESPECIE_DE_DOCUMENTO_LETRA_DE_CAMBIO = 'LC';
    const ESPECIE_DE_DOCUMENTO_MENSALIDADE_ESCOLAR = 'ME';
    const ESPECIE_DE_DOCUMENTO_NOTA_DE_CREDITO_COMERCIAL = 'NCC';
    const ESPECIE_DE_DOCUMENTO_NOTA_DE_CREDITO_DE_EXPORTACAO = 'NCE';
    const ESPECIE_DE_DOCUMENTO_NOTA_DE_CREDITO_INSDUSTRIAL = 'NCI';
    const ESPECIE_DE_DOCUMENTO_NOTA_DE_CREDITO_RURAL = 'NCR';
    const ESPECIE_DE_DOCUMENTO_NOTA_DE_DEBITO = 'NT';
    const ESPECIE_DE_DOCUMENTO_NOTA_PROMISSORIA = 'NP';
    const ESPECIE_DE_DOCUMENTO_NOTA_PROMISSORIA_RURAL = 'Nota Promissória Rural';
    const ESPECIE_DE_DOCUMENTO_NOTA_DE_SEGURO = 'NS';
    const ESPECIE_DE_DOCUMENTO_OUTROS = 'Outros';
    const ESPECIE_DE_DOCUMENTO_PARCELA_DE_CONSORCIO = 'PC';
    const ESPECIE_DE_DOCUMENTO_RECIBO = 'RC';
    const ESPECIE_DE_DOCUMENTO_TRIPLICATA_MERCANTIL = 'Triplicata Mercantil';
    const ESPECIE_DE_DOCUMENTO_TRIPLICATA_DE_SERVICO = 'Triplicata de Servico';
    const ESPECIE_DE_DOCUMENTO_WARRANT = 'Warrant';

}
