<?php
namespace parallaxsolutions\yii2boletos\models;
class SantanderConstants {

    const CODIGO_DO_BANCO = '033';
    const TIPO_DE_REGISTRO_HEADER_DO_ARQUIVO = '0';
    const TIPO_DE_REGISTRO_HEADER_DO_LOTE = '1';
    const TIPO_DE_REGISTRO_DETALHE = '3';
    const TIPO_DE_REGISTRO_TRAILER_DO_LOTE = '5';
    const TIPO_DE_REGISTRO_TRAILER_DO_ARQUIVO = '9'; //
    const TIPO_DE_COBRANCA_REMESSA_COBRANCA_SIMPLES_SEM_REGISTRO_E_ELETRONICA_COM_REGISTRO = '1'; // Sem Registro e Eletrônica com Registro
    const TIPO_DE_COBRANCA_REMESSA_COBRANCA_CAUCIONADA_ELETRONICA_COM_REGISTRO_E_CONVENCIONAL_COM_REGISTRO = '3'; // Eletrônica com Registro e Convencional com Registro
    const TIPO_DE_COBRANCA_REMESSA_COBRANCA_DESCONTADA = '4'; // Eletrônica com Registro
    const TIPO_DE_COBRANCA_REMESSA_COBRANCA_SIMPLES_RAPIDA_COM_REGISTRO = '5'; // Rápida com Registro
    const TIPO_DE_COBRANCA_REMESSA_COBRANCA_CAUCIONADA_RAPIDA_COM_REGISTRO = '6'; // Rápida com Registro
    const TIPO_DE_COBRANCA_REMESSA_TRANSFERENCIA_DE_TITULARIDADE_SEM_DEVOLUCAO = '7'; // Cobrança Simples - Eletrônica com Registro e Rápida com Registro
    const TIPO_DE_COBRANCA_REMESSA_COBRANCA_CESSAO = '8'; // Eletrônica com Registro
    const TIPO_DE_COBRANCA_REMESSA_TRANSFERENCIA_DE_TITULARIDADE_COM_DEVOLUCAO = '9'; // Cobrança Simples - Eletrônica com Registro e Rápida com Registro
    const TIPO_DE_DOCUMENTO_TRADICIONAL = 1;
    const TIPO_DE_DOCUMENTO_ESCRITURAL = 2;
    const TIPO_DE_COBRANCA_RETORNO_COBRANCA_SIMPLES_1 = '1'; // Sem Registo
    const TIPO_DE_COBRANCA_RETORNO_COBRANCA_SIMPLES_2 = '2'; // Rápida com Registro, Eletrônica, 
    const TIPO_DE_COBRANCA_RETORNO_COBRANCA_CAUCIONADA_1 = '3'; // Eletrônica com Registro e Convencional com Registro
    const TIPO_DE_COBRANCA_RETORNO_COBRANCA_DESCONTADA = '4'; // Convencional com Registro / Eletrônica com Registro
    const TIPO_DE_COBRANCA_RETORNO_COBRANCA_CAUCIONADA_2 = '6'; // Rápida com Registro
    const TIPO_DE_COBRANCA_RETORNO_TRANSFERENCIA_DE_TITULARIDADE_SEM_DEVOLUCAO = '7'; // Cobrança Simples - Eletrônica com Registro e Rápida com Registro
    const TIPO_DE_COBRANCA_RETORNO_COBRANCA_CESSAO = '8'; // Eletrônica com Registro
    const TIPO_DE_COBRANCA_RETORNO_TRANSFERENCIA_DE_TITULARIDADE_COM_DEVOLUCAO = '9'; // Cobrança Simples - Eletrônica com registro e Rápida com Registro
    const FORMA_DE_CADASTRAMENTO_COBRANCA_REGISTRADA = '1'; // Rápida e Eletrônica com Registro
    const FORMA_DE_CADASTRAMENTO_COBRANCA_SEM_REGISTRO = '2';
    const CODIGO_DO_SEGMENTO_DO_REGISTRO_DETALHE_DO_TITULO = 'P'; // Registro obrigatório na remessa
    const CODIGO_DO_SEGMENTO_DO_REGISTRO_DETALHE_DO_PAGADOR_E_SACADOR_AVALISTA = 'Q'; // Registro obrigatório somente na remessa de título novos
    const CODIGO_DO_SEGMENTO_DO_REGISTRO_DETALHE_OUTRAS_INSTRUCOES = 'R'; // Registro opcional na remessa
    const CODIGO_DO_SEGMENTO_DO_REGISTRO_DETALHE_OUTRAS_MENSAGENS_NO_TITULO = 'S'; // Registro opcional na remessa
    const CODIGO_DO_SEGMENTO_DO_REGISTRO_DETALHE_DA_COBRANCA = 'T'; // Registro obrigatório no retorno
    const CODIGO_DO_SEGMENTO_DO_REGISTRO_DETALHE_DE_VALORES_E_OCORRENCIAS = 'U'; // Registro obrigatório no reotrno
    const CODIGO_DO_SEGMENTO_DO_REGISTRO_DETALHE_DE_CHEQUES_DO_PAGAMENTO = 'Y'; // Registro opcional no retorno
    const CODIGO_DE_MOVIMENTO_PARA_REMESSA_ENTRADA_DE_TITULO = 1;
    const CODIGO_DE_MOVIMENTO_PARA_REMESSA_PEDIDO_DE_BAIXA = 2;
    const CODIGO_DE_MOVIMENTO_PARA_REMESSA_CONCESSAO_DE_ABATIMENTO = 4;
    const CODIGO_DE_MOVIMENTO_PARA_REMESSA_CANCELAMENTO_DE_ABATIMENTO = 5;
    const CODIGO_DE_MOVIMENTO_PARA_REMESSA_ALTERACAO_DE_VENCIMENTO = 6;
    const CODIGO_DE_MOVIMENTO_PARA_REMESSA_ALTERACAO_DA_IDENTIFICACAO_DO_TITULO_NA_EMPRESA = 7;
    const CODIGO_DE_MOVIMENTO_PARA_REMESSA_ALTERACAO_SEU_NUMERO = 8;
    const CODIGO_DE_MOVIMENTO_PARA_REMESSA_PEDIDO_DE_PROTESTO = 9;
    const CODIGO_DE_MOVIMENTO_PARA_REMESSA_PEDIDO_DE_SUSTACAO_DE_PROTESTO = 18;
    const CODIGO_DE_MOVIMENTO_PARA_REMESSA_CONCESSAO_DE_DESCONTO = 10;
    const CODIGO_DE_MOVIMENTO_PARA_REMESSA_CANCELAMENTO_DE_DESCONTO = 11;
    const CODIGO_DE_MOVIMENTO_PARA_REMESSA_TRANSFERENCIA_DE_TITULARIDADE_AUTOMATICA = 12;
    const CODIGO_DE_MOVIMENTO_PARA_REMESSA_ALTERACAO_DE_OUTROS_DADOS = 31;
    const CODIGO_DE_MOVIMENTO_PARA_REMESSA_NAO_PROTESTAR = 98; // Não Protestar (Antes de iniciar o ciclo de protesto)
    const CODIGO_DO_JUROS_MORA_POR_DIA = '1'; // CODIGO DE JUROS DE MORA POR DIA (VALOR CALCULADO)  
    const ESPECIE_DO_TITULO_DM = '02'; // DUPLICATA MERCANTIL
    const ESPECIE_DO_TITULO_DS = '04'; // DUPLICATA DE SERVIÇO
    const ESPECIE_DO_TITULO_LC_1 = '07'; // LETRA DE CÂMBIO (SOMENTE PARA BANCO 353)
    const ESPECIE_DO_TITULO_LC_2 = '30'; // LETRA DE CÂMBIO (SOMENTE PARA BANCO 008)
    const ESPECIE_DO_TITULO_NP = '12'; // NOTA PROMISSORIA
    const ESPECIE_DO_TITULO_NR = '13'; // NOTA PROMISSORIA RURAL
    const ESPECIE_DO_TITULO_RC = '17'; // RECIBO
    const ESPECIE_DO_TITULO_AP = '20'; // APOLICE DE SEGURO
    const ESPECIE_DO_TITULO_DBP = '32'; // BOLETO DE PROPOSTA
    const ESPECIE_DO_TITULO_CH = '97'; // CHEQUE
    const ESPECIE_DO_TITULO_ND = '98'; // NOTA PROMISSORIA DIRETA
    const CODIGO_DE_MORA_VALOR_POR_DIA = '1';
    const CODIGO_DE_MORA_VALOR_TAXA_MENSAL = '2';
    const CODIGO_DE_MORA_VALOR_ISENTO = '3';
    const CODIGO_DE_MORA_VALOR_UTILIZAR_COMISSAO_PERMANENCIA_DO_BANCO_POR_DIA_DE_ATRASO = '4';
    const CODIGO_DE_MORA_VALOR_TOLERANCIA_VALOR_POR_DIA = '5';
    const CODIGO_DE_MORA_VALOR_TOLERANCIA_TAXA_MENSAL = '6';
    // TODO PARA CÓDIGO IGUAL 4, O CAMPO "TAXA MENSAL" NÂO DEVERÁ CONTER INFORMAÇÃO

    const CODIGO_DO_DESCONTO_ISENTO = '0'; // Informar o valor no campo "valor de desconto a ser concedido"
    const CODIGO_DO_DESCONTO_VALOR_FIXO_ATE_A_DATA_INFORMADA = '1'; // Informar o percentual no campo "percentual de desconto a ser concedido"
    const CODIGO_DO_DESCONTO_PERCENTUAL_ATE_A_DATA_INFORMADA = '2'; // Informar o percentual no campo "percentual de desconto a aser concedido"
    const CODIGO_DO_DESCONTO_VALOR_POR_ANTECIPACAO_POR_DIA_CORRIDO = '3'; // Informar o valor no campo "valor de desconto a ser concedido"
    const CODIGO_DO_DESCONTO_VALOR_POR_ANTECIPACAO_DIA_UTIL = '4'; // Informar o valor no campo "valor de desconto a ser concedido"
    /*
     *  TODO Para os códigos 1 e 2 será obrigatório a informação da "data"
     *  NOTA: é possível informar até duas ocorrências de decsonto, ver NOTA 23
     */
    const CODIGO_PARA_PROTESTO_NAO_PROTESTAR = '0';
    const CODIGO_PARA_PROTESTO_PROTESTAR_DIAS_CORRIDOS = '1';
    const CODIGO_PARA_PROTESTO_PROTESTAR_DIAS_UTEIS = '2';
    const CODIGO_PARA_PROTESTO_UTILIZAR_PERFIL_BENEFICIARIO = '3';
    const CODIGO_PARA_PROTESTO_CANCELAMENTO_DE_PROTESTO_AUTOMATICO = '9';
    const CODIGO_PARA_BAIXA_DEVOLUCAO_BAIXAR_DEVOLVER = '1';
    const CODIGO_PARA_BAIXA_DEVOLUCAO_NAO_BAIXAR_NAO_DEVOLVER = '2';
    const CODIGO_PARA_BAIXA_DEVOLUCAO_UTILIZAR_PERFIL_BENEFICIARIO = '3';
    const CODIGO_DA_MOEDA_REAL = '00';
    const CONTROLE_DE_RECIBOS_DE_CARNE_NAO_POSSUI_CARNE = '000';
    const CONTROLE_DE_RECIBOS_DE_CARNE_POSSUI_CARNE = '001';
    const TIPO_DE_INSCRICAO_DO_PAGADOR_SACADOR_AVALISITA_CPF = '1';
    const TIPO_DE_INSCRICAO_DO_PAGADOR_SACADOR_AVALISITA_CGC = '2';
    const TIPO_DE_INSCRICAO_DO_PAGADOR_SACADOR_AVALISITA_NAO_INFOMADO = '0';
    const TIPO_DE_INSCRICAO_DO_PAGADOR_SACADOR_AVALISITA_OUTROS = '9';
    //NOTA 40
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_ENTRADA_CONFIRMADA = 2;
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_ENTRADA_REJEITADA = 3;
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_TRANSFERENCIA_DE_CARTEIRA_ENTRADA = 4;
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_TRANSFERENCIA_DE_CARTEIRA_BAIXA = 5;
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_LIQUIDACAO = 6;
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_BAIXA = 9;
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_TITULOS_EM_CARTEIRA = 11; // Em ser
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_CONFIRMACAO_RECEBIMENTO_INSTRUCAO_DE_ABATIMENTO = 12;
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_CONFIRMACAO_RECEBIMENTO_INSTRUCAO_DE_CANCELAMENTO_ABATIMENTO = 13;
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_CONFIRMACAO_RECEBIMENTO_INSTRUCAO_ALTERACAO_DE_VENCIMENTO = 14;
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_LIQUIDACAO_APOS_BAIXA_OU_LIQUIDACAO_TITULO_NAO_REGISTRADO = 17;
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_CONFIRMACAO_RECEBIMENTO_INSTRUCAO_DE_PROTESTO = 19;
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_CONFIRMACAO_RECEBIMENTO_INSTRUCAO_DE_SUSTACAO_NAO_PROTESTAR = 20;
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_REMESSA_A_CARTORIO = 23; // Aponte em cartorio
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_RETIRADA_DE_CARTORIO_E_MANUTENCAO_EM_CARTEIRA = 24;
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_PROTESTO_E_BAIXADO = 25; // Baixar por ter sido protestado
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_INSTRUCAO_REJEITADA = 26;
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_CONFIRMACAO_DO_PEDIDO_DE_ALTERACAO_DE_OUTROS_DADOS = 27;
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_DEBITO_DE_TARIFAS_CUSTAS = 28;
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_OCORRENCIAS_DO_PAGADOR = 29;
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_ALTERACAO_DE_DADOS_REJEITADA = 30;
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_CODIGO_DE_IOF_INVALIDO = 32;
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_TITULO_DDA_RECONHECIDO_PELO_PAGADOR = 51;
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_TITULO_DDA_NAO_RECONHECIDO_PELO_PAGADOR = 52;
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_TITULO_DDA_RECUSADO_PELA_CIP = 53;
    const CODIGOS_DE_MOVIMENTO_PARA_RETORNO_PAGADOR_DDA = 54;
    // Notas 40-A, 40-C
    const REJEICAO_DE_REGISTRO_DETALHE_CODIGO_DO_BANCO_INVALIDO = '01';
    const REJEICAO_DE_REGISTRO_DETALHE_CODIGO_DO_REGISTRO_DETALHE_INVALIDO = '02';
    const REJEICAO_DE_REGISTRO_DETALHE_CODIGO_DO_SEGMENTO_INVALIDO = '03';
    const REJEICAO_DE_REGISTRO_DETALHE_CODIGO_DO_SEGMENTO_NAO_PERMITIDO_PARA_CARTEIRA = '04';
    const REJEICAO_DE_REGISTRO_DETALHE_CODIGO_DE_MOVIMENTO_INVALIDO = '05';
    const REJEICAO_DE_REGISTRO_DETALHE_TIPO_NUMERO_DE_INSCRICAO_DO_BENEFICIARIO_INVALIDOS = '06';
    const REJEICAO_DE_REGISTRO_DETALHE_AGENCIA_CONTA_DV_INVALIDO = '07';
    const REJEICAO_DE_REGISTRO_DETALHE_NOSSO_NUMERO_INVALIDO = '08';
    const REJEICAO_DE_REGISTRO_DETALHE_NOSSO_NUMERO_DUPLICADO = '09';
    const REJEICAO_DE_REGISTRO_DETALHE_CARTEIRA_INVALIDA = '10';
    const REJEICAO_DE_REGISTRO_DETALHE_FORMA_DE_CADASTRAMENTO_DO_TITULO_INVALIDO = '11'; // Se desconto, titulo rejeitado - operação de desconto / horário limite
    const REJEICAO_DE_REGISTRO_DETALHE_TIPO_DE_DOCUMENTO_INVALIDO = '12';
    const REJEICAO_DE_REGISTRO_DETALHE_IDENTIFICACAO_DA_EMISSAO_DO_BOLETO_INVALIDA = '13';
    const REJEICAO_DE_REGISTRO_DETALHE_IDENTIFICACAO_DA_DISTRIBUICAO_DO_BOLETO_INVALIDA = '14';
    const REJEICAO_DE_REGISTRO_DETALHE_CARACTERISTICAS_DA_COBRANCA_INCOMPATIVEIS = '15';
    const REJEICAO_DE_REGISTRO_DETALHE_DATA_DE_VENCIMENTO_INVALIDA = '16';
    const REJEICAO_DE_REGISTRO_DETALHE_DATA_DE_VENCIMENTO_ANTERIOR_A_DATA_DE_EMISSAO = '17';
    const REJEICAO_DE_REGISTRO_DETALHE_VENCIMENTO_FORA_DO_PRAZO_DE_OPERACAO = '18';
    const REJEICAO_DE_REGISTRO_DETALHE_TITULO_A_CARGO_DE_BANCOS_CORRESPONDENTES = '19'; // Com vencimento inferior a xx dias
    const REJEICAO_DE_REGISTRO_DETALHE_VALOR_DO_TITULO_INVALIDO = '20';
    const REJEICAO_DE_REGISTRO_DETALHE_ESPECIE_DO_TITULO_INVALIDA = '21';
    const REJEICAO_DE_REGISTRO_DETALHE_ESPECIE_NAO_PERMITIDA_PARA_A_CARTEIRA = '22';
    const REJEICAO_DE_REGISTRO_DETALHE_ACEITE_INVALIDO = '23';
    const REJEICAO_DE_REGISTRO_DETALHE_DATA_DE_EMISSAO_INVALIDA = '24';
    const REJEICAO_DE_REGISTRO_DETALHE_DATA_DE_EMISSAO_POSTERIOR_A_DATA_DE_ENTRADA = '25';
    const REJEICAO_DE_REGISTRO_DETALHE_CODIGO_DE_JUROS_DE_MORA_INVALIDO = '26';
    const REJEICAO_DE_REGISTRO_DETALHE_VALOR_TAXA_DE_JUROS_DE_MORA_INVALIDO = '27';
    const REJEICAO_DE_REGISTRO_DETALHE_CODIGO_DE_DESCONTO_INVALIDO = '28';
    const REJEICAO_DE_REGISTRO_DETALHE_VALOR_DO_DESCONTO_MAIOR_OU_IGUAL_AO_VALOR_DO_TITULO = '29';
    const REJEICAO_DE_REGISTRO_DETALHE_DESCONTO_A_CONCEDER_NAO_CONFERE = '30';
    const REJEICAO_DE_REGISTRO_DETALHE_CONCESSAO_DO_DESCONTO = '31'; // Já existe desconto anterior
    const REJEICAO_DE_REGISTRO_DETALHE_VALOR_DO_IOF = '32';
    const REJEICAO_DE_REGISTRO_DETALHE_VALOR_DO_ABATIMENTO_INVALIDO = '33';
    const REJEICAO_DE_REGISTRO_DETALHE_VALOR_DO_ABATIMENTO_MAIOR_OU_IGUAL_AO_VALOR_DO_TITULO = '34';
    const REJEICAO_DE_REGISTRO_DETALHE_ABATIMENTO_A_CONCEDER_NAO_CONFERE = '35';
    const REJEICAO_DE_REGISTRO_DETALHE_CONCESSAO_DE_ABATIMENTO = '36'; // Já existe abatimento anterior
    const REJEICAO_DE_REGISTRO_DETALHE_CODIGO_PARA_PROTESTO_INVALIDO = '37';
    const REJEICAO_DE_REGISTRO_DETALHE_PRAZO_PARA_PROTESTO_INVALIDO = '38';
    const REJEICAO_DE_REGISTRO_DETALHE_PEDIDO_DE_PROTESTO_NAO_PERMITIDO_PARA_O_TITULO = '39';
    const REJEICAO_DE_REGISTRO_DETALHE_TITULO_COM_ORDEM_DE_PROTESTO_EMITIDA = '40';
    const REJEICAO_DE_REGISTRO_DETALHE_PEDIDO_DE_CANCELAMENTO_SUSTACAO_PARA_TITULOS_SEM_INSTRUCAO_DE_PROTESTO = '41';
    const REJEICAO_DE_REGISTRO_DETALHE_CODIGO_PARA_BAIXA_DEVOLUCAO_INVALIDO = '42';
    const REJEICAO_DE_REGISTRO_DETALHE_PRAZO_PARA_BAIXA_DEVOLUCAO_INVALIDO = '43';
    const REJEICAO_DE_REGISTRO_DETALHE_CODIGO_DE_MOEDA_INVALIDO = '44';
    const REJEICAO_DE_REGISTRO_DETALHE_NOME_DO_PAGADOR_NAO_INFORMADO = '45';
    const REJEICAO_DE_REGISTRO_DETALHE_TIPO_NUMERO_DE_INSCRICAO_DO_PAGADOR_INVALIDOS = '46';
    const REJEICAO_DE_REGISTRO_DETALHE_ENDERECO_DO_PAGADOR_NAO_INFORMADO = '47';
    const REJEICAO_DE_REGISTRO_DETALHE_CEP_INVALIDO = '48';
    const REJEICAO_DE_REGISTRO_DETALHE_CEP_SEM_PRACA_DE_COBRANCA = '49'; // Não localizado
    const REJEICAO_DE_REGISTRO_DETALHE_CEP_REFERENTE_A_UM_BANCO_CORRESPONDENTE = '50';
    const REJEICAO_DE_REGISTRO_DETALHE_CEP_INCOMPATIVEL_COM_A_UNIDADE_DE_FEDERACAO = '51';
    const REJEICAO_DE_REGISTRO_DETALHE_UNIDADE_DE_FEDERACAO_INVALIDA = '52';
    const REJEICAO_DE_REGISTRO_DETALHE_TIPO_NUMERO_DE_INSCRICAO_DO_SACADOR_AVALISTA_INVALIDOS = '53';
    const REJEICAO_DE_REGISTRO_DETALHE_SACADOR_AVALISTA_NAO_INFORMADO = '54';
    const REJEICAO_DE_REGISTRO_DETALHE_NOSSO_NUMERO_NO_BANCO_CORRESPONDENTE_NAO_INFORMADO = '55';
    const REJEICAO_DE_REGISTRO_DETALHE_CODIGO_DO_BANCO_CORRESPONDENTE_NAO_INFORMADO = '56';
    const REJEICAO_DE_REGISTRO_DETALHE_CODIGO_DA_MULTA_INVALIDO = '57';
    const REJEICAO_DE_REGISTRO_DETALHE_DATA_DA_MULTA_INVALIDA = '58';
    const REJEICAO_DE_REGISTRO_DETALHE_VALOR_PERCENTUAL_DA_MULTA_INVALIDO = '59';
    const REJEICAO_DE_REGISTRO_DETALHE_MOVIMENTO_PARA_TITULO_NAO_CADASTRADO = '60';
    const REJEICAO_DE_REGISTRO_DETALHE_ALTERACAO_DE_AGENCIA_COBRADORA_DV_INVALIDA = '61';
    const REJEICAO_DE_REGISTRO_DETALHE_TIPO_DE_IMPRESSAO_INVALIDO = '62';
    const REJEICAO_DE_REGISTRO_DETALHE_ENTRADA_PARA_TITULO_JA_CADASTRADO = '63';
    const REJEICAO_DE_REGISTRO_DETALHE_NUMERO_DE_LINHAS_INVALIDO = '64';
    const REJEICAO_DE_REGISTRO_DETALHE_IDENTIFICADOR_QUANTIDADE_DE_PARCELAS_DE_CARNE_INVALIDO = '90';
    // Nota 40 C
    const CODIGO_DE_LIQUIDACAO_POR_SALDO = '01';
    const CODIGO_DE_LIQUIDACAO_POR_CONTA = '02';
    const CODIGO_DE_LIQUIDACAO_NO_PROPRIO_BANCO = '03';
    const CODIGO_DE_LIQUIDACAO_COMPENSACAO_ELETRONICA = '04';
    const CODIGO_DE_LIQUIDACAO_COMPENSACAO_CONVENCIONAL = '05';
    const CODIGO_DE_LIQUIDACAO_ARQUIVO_MAGNETO = '06';
    const CODIGO_DE_LIQUIDACAO_APOS_FERIADO_LOCAL = '07';
    const CODIGO_DE_LIQUIDACAO_EM_CARTORIO = '08';
    const CODIGO_DE_BAIXA_COMANDADA_BANCO = '09';
    const CODIGO_DE_BAIXA_COMANDADA_CLIENTE_ARQUIVO = '10';
    const CODIGO_DE_BAIXA_COMANDADA_CLIENTE_ON_LINE = '11';
    const CODIGO_DE_BAIXA_DECURSO_PRAZO_CLIENTE = '12';
    const CODIGO_DE_BAIXA_DECURSO_PRAZO_BANCO = '13';
    //nota 41
    const OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_NAO_RECEBEU_A_MERCADORIA = '0101';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_A_MERCADORIA_CHEGOU_ATRASADA = '0102';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_A_MERCADORIA_CHEGOU_AVARIADA = '0103';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_A_MERCADORIA_NAO_CONFERE_COM_O_PEDIDO = '0104';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_A_MERCADORIA_CHEGOU_INCOMPLETA = '0105';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_A_MERCADORIA_ESTA_A_DISPOSICAO_AO_BENEFICIARIO = '0106';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_DEVOLVEU_A_MERCADORIA = '0107';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_A_MERCADORIA_ESTA_EM_DESACORDO_COM_A_NOTA_FISCAL = '0108';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_NADA_DEVE_OU_COMPROU = '0109';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_NAO_RECEBEU_A_FATURA = '0201';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_O_PEDIDO_DE_COMPRA_FOI_CANCELADO = '0202';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_A_DUPLICATA_FOI_CANCELADA = '0203';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_NAO_TER_RECEBIDO_A_MERCADORIA_NOTA_FISCAL_FATURA = '0204';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_A_DUPLICATA_OU_FATURA_ESTA_INCORRETA = '0205';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_O_VALOR_ESTA_INCORRETO = '0206';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_O_FATURAMENTO_E_INDEVIDO = '0207';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_NAO_LOCALIZOU_O_PEDIDO_DE_COMPRA = '0208';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_O_VENCIMENTO_CORRETO_E = '0301';
    const OCORRENCIAS_ALEGACOES_PAGADOR_SOLICITA_A_PRORROGACAO_DE_VENCIMENTO_PARA = '0302';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ACEITA_SE_VENCIMENTO_PRORROGADO_PARA = '0303';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_PAGARA_O_TITULO_EM = '0304';
    const OCORRENCIAS_ALEGACOES_PAGADOR_PAGOU_O_TITULO_DIRETAMENTE_AO_BENEFICIARIO_EM = '0305';
    const OCORRENCIAS_ALEGACOES_PAGADOR_PAGARA_O_TITULO_DIRETAMENTE_AO_BENEFICIARIO_EM = '0306';
    const OCORRENCIAS_ALEGACOES_PAGADOR_NAO_FOI_LOCALIZADO_CONFIRMAR_ENDERECO = '0401';
    const OCORRENCIAS_ALEGACOES_PAGADOR_MUDOU_SE_TRANSFERIU_DE_DOMICILIO = '0402';
    const OCORRENCIAS_ALEGACOES_PAGADOR_NAO_RECEBE_NO_ENDERECO_INDICADO = '0403';
    const OCORRENCIAS_ALEGACOES_PAGADOR_DESCONHECIDO_NO_LOCAL = '0404';
    const OCORRENCIAS_ALEGACOES_PAGADOR_RESIDE_FORA_DO_PERIMETRO = '0405';
    const OCORRENCIAS_ALEGACOES_PAGADOR_COM_ENDERECO_INCOMPLETO = '0406';
    const OCORRENCIAS_ALEGACOES_NAO_FOI_LOCALIZADO_O_NUMERO_CONSTANTE_NO_ENDEREÇO_DO_TITULO = '0407';
    const OCORRENCIAS_ALEGACOES_ENDERECO_NAO_LOCALIZADO_OU_NAO_CONSTA_NOS_GUIAS_DA_CIDADE = '0408';
    const OCORRENCIAS_ALEGACOES_ENDERECO_DO_PAGADOR_ALTERADO_PARA = '0409';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_TEM_DESCONTO_OU_ABATIMENTO_DE = '0501';
    const OCORRENCIAS_ALEGACOES_PAGADOR_SOLICITA_DESCONTO_OU_ABATIMENTO_DE = '0502';
    const OCORRENCIAS_ALEGACOES_PAGADOR_SOLICITA_DISPENSA_DOS_JUROS_DE_MORA = '0503';
    const OCORRENCIAS_ALEGACOES_PAGADOR_SE_RECUSA_A_PAGAR_JUROS = '0504';
    const OCORRENCIAS_ALEGACOES_PAGADOR_SE_RECUSA_A_PAGAR_COMISSAO_DE_PERMANENCIA = '0505';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ESTA_EM_REGIME_DE_CONCORDATA = '0601';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ESTA_EM_REGIME_DE_FALENCIA = '0602';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_MANTEM_ENTENDIMENTOS_COM_PAGADOR = '0603';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ESTA_EM_ENTENDIMENTOS_COM_O_BENEFICIARIO = '0604';
    const OCORRENCIAS_ALEGACOES_PAGADOR_ESTA_VIAJANDO = '0605';
    const OCORRENCIAS_ALEGACOES_PAGADOR_RECUSOU_SE_A_ACEITAR_O_TITULO = '0606';
    const OCORRENCIAS_ALEGACOES_PAGADOR_SUSTOU_PROTESTO_JUDICIALMENTE = '0607';
    const OCORRENCIAS_ALEGACOES_EMPREGADO_RECUSOU_SE_A_RECEBER_O_TITULO = '0608';
    const OCORRENCIAS_ALEGACOES_TITULO_REAPRESENTADO_AO_PAGADOR = '0609';
    const OCORRENCIAS_ALEGACOES_ESTAMOS_NOS_DIRIGINDO_AO_NOSSO_CORRESPONDENTE = '0610';
    const OCORRENCIAS_ALEGACOES_CORRESPONDENTE_NAO_SE_INTERESSA_PELO_PROTESTO = '0611';
    const OCORRENCIAS_ALEGACOES_PAGADOR_NAO_ATENDE_AOS_AVISOS_DE_NOSSOS_CORRESPONDENTES = '0612';
    const OCORRENCIAS_ALEGACOES_TITULO_ESTA_SENDO_ENCAMINHADO_AO_CORRESPONDENTE = '0613';
    const OCORRENCIAS_ALEGACOES_ENTREGA_FRANCO_DE_PAGAMENTO_AO_PAGADOR = '0614';
    const OCORRENCIAS_ALEGACOES_ENTREGA_FRANCO_DE_PAGAMENTO_AO_REPRESENTANTE = '0615';
    const OCORRENCIAS_ALEGACOES_A_ENTREGA_FRANCO_DE_PAGAMENTO_E_DIFICIL = '0616';
    const OCORRENCIAS_ALEGACOES_TITULO_RECUSADO_PELO_CARTORIO = '0617';
    //segmento q
    const TIPO_INSCRICAO_DO_PAGADOR_NAO_INFORMADO = 0;
    const TIPO_INSCRICAO_DO_PAGADOR_CPF = 1;
    const TIPO_INSCRICAO_DO_PAGADOR_CGC = 2; //CNPJ
    const TIPO_INSCRICAO_DO_PAGADOR_OUTROS = 9;
    //segmento r
    const CODIGO_DA_MULTA_PORCENTAGEM = 2;
    //lote
    const TIPO_DE_INSCRICAO_DA_EMPRESA_CPF = 1;
    const TIPO_DE_INSCRICAO_DA_EMPRESA_CNPJ = 2;

    public static function codigoDeMovimentoParaRetornoLabel($codigo = null) {
        $labels = array(
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_ENTRADA_CONFIRMADA => 'Entrada confirmada',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_ENTRADA_REJEITADA => 'Entrada rejeitada',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_TRANSFERENCIA_DE_CARTEIRA_ENTRADA => 'Transferência de carteira/entrada',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_TRANSFERENCIA_DE_CARTEIRA_BAIXA => 'Transferência de carteira/baixa',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_LIQUIDACAO => 'Liquidação',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_BAIXA => 'Baixa',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_TITULOS_EM_CARTEIRA => 'Títulos em carteira',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_CONFIRMACAO_RECEBIMENTO_INSTRUCAO_DE_ABATIMENTO => 'Confirmação recebimento instrução de abatimento',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_CONFIRMACAO_RECEBIMENTO_INSTRUCAO_DE_CANCELAMENTO_ABATIMENTO => 'Confirmação recebimento instrução de cancelamento abatimento',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_CONFIRMACAO_RECEBIMENTO_INSTRUCAO_ALTERACAO_DE_VENCIMENTO => 'Confirmação recebimento instrução alteração de vencimento',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_LIQUIDACAO_APOS_BAIXA_OU_LIQUIDACAO_TITULO_NAO_REGISTRADO => 'Liquidação após baixa ou liquidação título não registrado',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_CONFIRMACAO_RECEBIMENTO_INSTRUCAO_DE_PROTESTO => 'Confirmação recebimento instrução de protesto',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_CONFIRMACAO_RECEBIMENTO_INSTRUCAO_DE_SUSTACAO_NAO_PROTESTAR => 'Confirmação recebimento instrução de sustação/Não protestar',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_REMESSA_A_CARTORIO => 'Remessa a cartório (aponte em cartório)',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_RETIRADA_DE_CARTORIO_E_MANUTENCAO_EM_CARTEIRA => 'Retirada de cartório e manutenção em carteira',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_PROTESTO_E_BAIXADO => 'Protesto e baixado (baixa por ter sido protestado)',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_INSTRUCAO_REJEITADA => 'Instrução rejeitada',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_CONFIRMACAO_DO_PEDIDO_DE_ALTERACAO_DE_OUTROS_DADOS => 'Confirmação do pedido de alteração de outros dados',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_DEBITO_DE_TARIFAS_CUSTAS => 'Débito de tarifas custas',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_OCORRENCIAS_DO_PAGADOR => 'Ocorrências do pagador',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_ALTERACAO_DE_DADOS_REJEITADA => 'Alteração de dados rejeitada',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_CODIGO_DE_IOF_INVALIDO => 'Código de IOF inválido',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_TITULO_DDA_RECONHECIDO_PELO_PAGADOR => 'Título DDA reconhecido pelo pagador',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_TITULO_DDA_NAO_RECONHECIDO_PELO_PAGADOR => 'Título DDA não reconhecido pelo pagador',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_TITULO_DDA_RECUSADO_PELA_CIP => 'Título DDA recusado pela CIP',
            self::CODIGOS_DE_MOVIMENTO_PARA_RETORNO_PAGADOR_DDA => 'Pagador DDA',
        );
        if ($codigo === null) {
            return $labels;
        }
        return $labels[$codigo];
    }

    public static function codigoDeMovimentoParaRemessaLabel($codigo = null) {
        $labels = array(
            self::CODIGO_DE_MOVIMENTO_PARA_REMESSA_ENTRADA_DE_TITULO => 'Entrada de título',
            self::CODIGO_DE_MOVIMENTO_PARA_REMESSA_PEDIDO_DE_BAIXA => 'Pedido de baixa',
            self::CODIGO_DE_MOVIMENTO_PARA_REMESSA_ALTERACAO_DE_VENCIMENTO => 'Alteração de vencimento',
            self::CODIGO_DE_MOVIMENTO_PARA_REMESSA_ALTERACAO_DE_OUTROS_DADOS => 'Alteração de outros dados',
        );
        if ($codigo === null) {
            return $labels;
        }
        return $labels[$codigo];
    }
    
    public function rejeicaoDeRegistroDetalheLabels($index) {
        $label = array(
            self::REJEICAO_DE_REGISTRO_DETALHE_CODIGO_DO_BANCO_INVALIDO => 'Código do banco invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_CODIGO_DO_REGISTRO_DETALHE_INVALIDO => 'Código do registro detalhe invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_CODIGO_DO_SEGMENTO_INVALIDO => 'Código do segmento invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_CODIGO_DO_SEGMENTO_NAO_PERMITIDO_PARA_CARTEIRA => 'Código do segmento não permitido para carteira',
            self::REJEICAO_DE_REGISTRO_DETALHE_CODIGO_DE_MOVIMENTO_INVALIDO => 'Código de movimento invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_TIPO_NUMERO_DE_INSCRICAO_DO_BENEFICIARIO_INVALIDOS => 'Tipo número de inscrição do beneficiário inválidos',
            self::REJEICAO_DE_REGISTRO_DETALHE_AGENCIA_CONTA_DV_INVALIDO => 'Agencia conta DV invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_NOSSO_NUMERO_INVALIDO => 'Nosso número invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_NOSSO_NUMERO_DUPLICADO => 'Nosso número duplicado',
            self::REJEICAO_DE_REGISTRO_DETALHE_CARTEIRA_INVALIDA => 'Carteira invalida',
            self::REJEICAO_DE_REGISTRO_DETALHE_FORMA_DE_CADASTRAMENTO_DO_TITULO_INVALIDO => 'Forma de cadastramento do título invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_TIPO_DE_DOCUMENTO_INVALIDO => 'Tipo de documento invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_IDENTIFICACAO_DA_EMISSAO_DO_BOLETO_INVALIDA => 'Identificação da emissão do boleto invalida',
            self::REJEICAO_DE_REGISTRO_DETALHE_IDENTIFICACAO_DA_DISTRIBUICAO_DO_BOLETO_INVALIDA => 'Identificação da distribuição do boleto invalida',
            self::REJEICAO_DE_REGISTRO_DETALHE_CARACTERISTICAS_DA_COBRANCA_INCOMPATIVEIS => 'Características da cobrança incompatíveis',
            self::REJEICAO_DE_REGISTRO_DETALHE_DATA_DE_VENCIMENTO_INVALIDA => 'Data de vencimento invalida',
            self::REJEICAO_DE_REGISTRO_DETALHE_DATA_DE_VENCIMENTO_ANTERIOR_A_DATA_DE_EMISSAO => 'Data de vencimento anterior à data de emissão',
            self::REJEICAO_DE_REGISTRO_DETALHE_VENCIMENTO_FORA_DO_PRAZO_DE_OPERACAO => 'Vencimento fora do prazo de operação',
            self::REJEICAO_DE_REGISTRO_DETALHE_TITULO_A_CARGO_DE_BANCOS_CORRESPONDENTES => 'Título a cargo de bancos correspondentes',
            self::REJEICAO_DE_REGISTRO_DETALHE_VALOR_DO_TITULO_INVALIDO => 'Valor do título invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_ESPECIE_DO_TITULO_INVALIDA => 'Espécie do título invalida',
            self::REJEICAO_DE_REGISTRO_DETALHE_ESPECIE_NAO_PERMITIDA_PARA_A_CARTEIRA => 'Espécie não permitida para a carteira',
            self::REJEICAO_DE_REGISTRO_DETALHE_ACEITE_INVALIDO => 'Aceite invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_DATA_DE_EMISSAO_INVALIDA => 'Data de emissão invalida',
            self::REJEICAO_DE_REGISTRO_DETALHE_DATA_DE_EMISSAO_POSTERIOR_A_DATA_DE_ENTRADA => 'Data de emissão posterior a data de entrada',
            self::REJEICAO_DE_REGISTRO_DETALHE_CODIGO_DE_JUROS_DE_MORA_INVALIDO => 'Código de juros de mora invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_VALOR_TAXA_DE_JUROS_DE_MORA_INVALIDO => 'Valor taxa de juros de mora invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_CODIGO_DE_DESCONTO_INVALIDO => 'Código de desconto invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_VALOR_DO_DESCONTO_MAIOR_OU_IGUAL_AO_VALOR_DO_TITULO => 'Valor do desconto maior ou igual ao valor do título',
            self::REJEICAO_DE_REGISTRO_DETALHE_DESCONTO_A_CONCEDER_NAO_CONFERE => 'Desconto a conceder não confere',
            self::REJEICAO_DE_REGISTRO_DETALHE_CONCESSAO_DO_DESCONTO => 'Concessão do desconto',
            self::REJEICAO_DE_REGISTRO_DETALHE_VALOR_DO_IOF => 'Valor do IOF',
            self::REJEICAO_DE_REGISTRO_DETALHE_VALOR_DO_ABATIMENTO_INVALIDO => 'Valor do abatimento invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_VALOR_DO_ABATIMENTO_MAIOR_OU_IGUAL_AO_VALOR_DO_TITULO => 'Valor do abatimento maior ou igual ao valor do título',
            self::REJEICAO_DE_REGISTRO_DETALHE_ABATIMENTO_A_CONCEDER_NAO_CONFERE => 'Abatimento a conceder não confere',
            self::REJEICAO_DE_REGISTRO_DETALHE_CONCESSAO_DE_ABATIMENTO => 'Concessão de abatimento',
            self::REJEICAO_DE_REGISTRO_DETALHE_CODIGO_PARA_PROTESTO_INVALIDO => 'Código para protesto invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_PRAZO_PARA_PROTESTO_INVALIDO => 'Prazo para protesto invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_PEDIDO_DE_PROTESTO_NAO_PERMITIDO_PARA_O_TITULO => 'Pedido de protesto não permitido para o título',
            self::REJEICAO_DE_REGISTRO_DETALHE_TITULO_COM_ORDEM_DE_PROTESTO_EMITIDA => 'Título com ordem de protesto emitida',
            self::REJEICAO_DE_REGISTRO_DETALHE_PEDIDO_DE_CANCELAMENTO_SUSTACAO_PARA_TITULOS_SEM_INSTRUCAO_DE_PROTESTO => 'Pedido de cancelamento sustação para títulos sem instrução de protesto',
            self::REJEICAO_DE_REGISTRO_DETALHE_CODIGO_PARA_BAIXA_DEVOLUCAO_INVALIDO => 'Código para baixa devolução invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_PRAZO_PARA_BAIXA_DEVOLUCAO_INVALIDO => 'Prazo para baixa devolução invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_CODIGO_DE_MOEDA_INVALIDO => 'Código de moeda invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_NOME_DO_PAGADOR_NAO_INFORMADO => 'Nome do pagador não informado',
            self::REJEICAO_DE_REGISTRO_DETALHE_TIPO_NUMERO_DE_INSCRICAO_DO_PAGADOR_INVALIDOS => 'Tipo número de inscrição do pagador inválidos',
            self::REJEICAO_DE_REGISTRO_DETALHE_ENDERECO_DO_PAGADOR_NAO_INFORMADO => 'Endereço do pagador não informado',
            self::REJEICAO_DE_REGISTRO_DETALHE_CEP_INVALIDO => 'CEP invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_CEP_SEM_PRACA_DE_COBRANCA => 'CEP sem praça de cobrança',
            self::REJEICAO_DE_REGISTRO_DETALHE_CEP_REFERENTE_A_UM_BANCO_CORRESPONDENTE => 'CEP referente a um banco correspondente',
            self::REJEICAO_DE_REGISTRO_DETALHE_CEP_INCOMPATIVEL_COM_A_UNIDADE_DE_FEDERACAO => 'CEP incompatível com a unidade de federação',
            self::REJEICAO_DE_REGISTRO_DETALHE_UNIDADE_DE_FEDERACAO_INVALIDA => 'Unidade de federação invalida',
            self::REJEICAO_DE_REGISTRO_DETALHE_TIPO_NUMERO_DE_INSCRICAO_DO_SACADOR_AVALISTA_INVALIDOS => 'Tipo número de inscrição do sacador avalista inválidos',
            self::REJEICAO_DE_REGISTRO_DETALHE_SACADOR_AVALISTA_NAO_INFORMADO => 'Sacador avalista não informado',
            self::REJEICAO_DE_REGISTRO_DETALHE_NOSSO_NUMERO_NO_BANCO_CORRESPONDENTE_NAO_INFORMADO => 'Nosso número no banco correspondente não informado',
            self::REJEICAO_DE_REGISTRO_DETALHE_CODIGO_DO_BANCO_CORRESPONDENTE_NAO_INFORMADO => 'Código do banco correspondente não informado',
            self::REJEICAO_DE_REGISTRO_DETALHE_CODIGO_DA_MULTA_INVALIDO => 'Código da multa invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_DATA_DA_MULTA_INVALIDA => 'Data da multa invalida',
            self::REJEICAO_DE_REGISTRO_DETALHE_VALOR_PERCENTUAL_DA_MULTA_INVALIDO => 'Valor percentual da multa invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_MOVIMENTO_PARA_TITULO_NAO_CADASTRADO => 'Movimento para título não cadastrado',
            self::REJEICAO_DE_REGISTRO_DETALHE_ALTERACAO_DE_AGENCIA_COBRADORA_DV_INVALIDA => 'Alteração de agencia cobradora DV invalida',
            self::REJEICAO_DE_REGISTRO_DETALHE_TIPO_DE_IMPRESSAO_INVALIDO => 'Tipo de impressão invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_ENTRADA_PARA_TITULO_JA_CADASTRADO => 'Entrada para título já cadastrado',
            self::REJEICAO_DE_REGISTRO_DETALHE_NUMERO_DE_LINHAS_INVALIDO => 'Número de linhas invalido',
            self::REJEICAO_DE_REGISTRO_DETALHE_IDENTIFICADOR_QUANTIDADE_DE_PARCELAS_DE_CARNE_INVALIDO => 'Identificador quantidade de parcelas de carne invalido',
        );
        return $label[$index];
    }

    public function codigoDeLiquidacaoLabels($index) {
        $label = array(
            self::CODIGO_DE_LIQUIDACAO_POR_SALDO => 'Código de liquidação por saldo',
            self::CODIGO_DE_LIQUIDACAO_POR_CONTA => 'Código de liquidação por conta',
            self::CODIGO_DE_LIQUIDACAO_NO_PROPRIO_BANCO => 'Código de liquidação no próprio banco',
            self::CODIGO_DE_LIQUIDACAO_COMPENSACAO_ELETRONICA => 'Código de liquidação compensação eletrônica',
            self::CODIGO_DE_LIQUIDACAO_COMPENSACAO_CONVENCIONAL => 'Código de liquidação compensação convencional',
            self::CODIGO_DE_LIQUIDACAO_ARQUIVO_MAGNETO => 'Código de liquidação arquivo magneto',
            self::CODIGO_DE_LIQUIDACAO_APOS_FERIADO_LOCAL => 'Código de liquidação após feriado local',
            self::CODIGO_DE_LIQUIDACAO_EM_CARTORIO => 'Código de liquidação em cartório',
        );
        return $label[$index];
    }

    public function codigoDeBaixaLabels($index) {
        $label = array(
            self::CODIGO_DE_BAIXA_COMANDADA_BANCO => 'Código de baixa comandada banco',
            self::CODIGO_DE_BAIXA_COMANDADA_CLIENTE_ARQUIVO => 'Código de baixa comandada cliente arquivo',
            self::CODIGO_DE_BAIXA_COMANDADA_CLIENTE_ON_LINE => 'Código de baixa comandada cliente on-line',
            self::CODIGO_DE_BAIXA_DECURSO_PRAZO_CLIENTE => 'Código de baixa decurso prazo cliente',
            self::CODIGO_DE_BAIXA_DECURSO_PRAZO_BANCO => 'Código de baixa decurso prazo banco',
        );
        return $label[$index];
    }

    public function ocorrenciasEAlegacoesLabels($index) {
        $label = array(
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_NAO_RECEBEU_A_MERCADORIA => 'Pagador alega que não recebeu a mercadoria',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_A_MERCADORIA_CHEGOU_ATRASADA => 'Pagador alega que a mercadoria chegou atrasada',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_A_MERCADORIA_CHEGOU_AVARIADA => 'Pagador alega que a mercadoria chegou avariada',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_A_MERCADORIA_NAO_CONFERE_COM_O_PEDIDO => 'Pagador alega que a mercadoria não confere com o pedido',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_A_MERCADORIA_CHEGOU_INCOMPLETA => 'Pagador alega que a mercadoria chegou incompleta',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_A_MERCADORIA_ESTA_A_DISPOSICAO_AO_BENEFICIARIO => 'Pagador alega que a mercadoria está a disposição ao beneficiário',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_DEVOLVEU_A_MERCADORIA => 'Pagador alega que devolveu a mercadoria',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_A_MERCADORIA_ESTA_EM_DESACORDO_COM_A_NOTA_FISCAL => 'Pagador alega que a mercadoria está em desacordo com a nota fiscal',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_NADA_DEVE_OU_COMPROU => 'Pagador alega que nada deve ou comprou',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_NAO_RECEBEU_A_FATURA => 'Pagador alega que não recebeu a fatura',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_O_PEDIDO_DE_COMPRA_FOI_CANCELADO => 'Pagador alega que o pedido de compra foi cancelado',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_A_DUPLICATA_FOI_CANCELADA => 'Pagador alega que a duplicata foi cancelada',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_NAO_TER_RECEBIDO_A_MERCADORIA_NOTA_FISCAL_FATURA => 'Pagador alega não ter recebido a mercadoria nota fiscal fatura',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_A_DUPLICATA_OU_FATURA_ESTA_INCORRETA => 'Pagador alega que a duplicata/fatura está incorreta',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_O_VALOR_ESTA_INCORRETO => 'Pagador alega que o valor está incorreto',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_O_FATURAMENTO_E_INDEVIDO => 'Pagador alega que o faturamento e indevido',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_NAO_LOCALIZOU_O_PEDIDO_DE_COMPRA => 'Pagador alega que não localizou o pedido de compra',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_O_VENCIMENTO_CORRETO_E => 'Pagador alega que o vencimento correto e',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_SOLICITA_A_PRORROGACAO_DE_VENCIMENTO_PARA => 'Pagador solicita a prorrogação de vencimento para',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ACEITA_SE_VENCIMENTO_PRORROGADO_PARA => 'Pagador aceita se vencimento prorrogado para',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_PAGARA_O_TITULO_EM => 'Pagador alega que pagara o título em',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_PAGOU_O_TITULO_DIRETAMENTE_AO_BENEFICIARIO_EM => 'Pagador pagou o título diretamente ao beneficiário em',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_PAGARA_O_TITULO_DIRETAMENTE_AO_BENEFICIARIO_EM => 'Pagador pagará o título diretamente ao beneficiário em',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_NAO_FOI_LOCALIZADO_CONFIRMAR_ENDERECO => 'Pagador não foi localizado confirmar endereço',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_MUDOU_SE_TRANSFERIU_DE_DOMICILIO => 'Pagador mudou se transferiu de domicilio',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_NAO_RECEBE_NO_ENDERECO_INDICADO => 'Pagador não recebe no endereço indicado',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_DESCONHECIDO_NO_LOCAL => 'Pagador desconhecido no local',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_RESIDE_FORA_DO_PERIMETRO => 'Pagador reside fora do perímetro',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_COM_ENDERECO_INCOMPLETO => 'Pagador com endereço incompleto',
            self::OCORRENCIAS_ALEGACOES_NAO_FOI_LOCALIZADO_O_NUMERO_CONSTANTE_NO_ENDEREÇO_DO_TITULO => 'Nao foi localizado o número constante no endereço do título',
            self::OCORRENCIAS_ALEGACOES_ENDERECO_NAO_LOCALIZADO_OU_NAO_CONSTA_NOS_GUIAS_DA_CIDADE => 'Endereco não localizado/não consta nos guias da cidade',
            self::OCORRENCIAS_ALEGACOES_ENDERECO_DO_PAGADOR_ALTERADO_PARA => 'Endereco do pagador alterado para',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_TEM_DESCONTO_OU_ABATIMENTO_DE => 'Pagador alega que tem desconto ou abatimento de',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_SOLICITA_DESCONTO_OU_ABATIMENTO_DE => 'Pagador solicita desconto ou abatimento de',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_SOLICITA_DISPENSA_DOS_JUROS_DE_MORA => 'Pagador solicita dispensa dos juros de mora',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_SE_RECUSA_A_PAGAR_JUROS => 'Pagador se recusa a pagar juros',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_SE_RECUSA_A_PAGAR_COMISSAO_DE_PERMANENCIA => 'Pagador se recusa a pagar comissão de permanência',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ESTA_EM_REGIME_DE_CONCORDATA => 'Pagador esta em regime de concordata',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ESTA_EM_REGIME_DE_FALENCIA => 'Pagador está em regime de falência',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ALEGA_QUE_MANTEM_ENTENDIMENTOS_COM_PAGADOR => 'Pagador alega que mantem entendimentos com pagador',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ESTA_EM_ENTENDIMENTOS_COM_O_BENEFICIARIO => 'Pagador está em entendimentos com o beneficiário',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_ESTA_VIAJANDO => 'Pagador está viajando',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_RECUSOU_SE_A_ACEITAR_O_TITULO => 'Pagador recusou se a aceitar o título',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_SUSTOU_PROTESTO_JUDICIALMENTE => 'Pagador sustou protesto judicialmente',
            self::OCORRENCIAS_ALEGACOES_EMPREGADO_RECUSOU_SE_A_RECEBER_O_TITULO => 'Empregado recusou se a receber o título',
            self::OCORRENCIAS_ALEGACOES_TITULO_REAPRESENTADO_AO_PAGADOR => 'Titulo reapresentado ao pagador',
            self::OCORRENCIAS_ALEGACOES_ESTAMOS_NOS_DIRIGINDO_AO_NOSSO_CORRESPONDENTE => 'Estamos nos dirigindo ao nosso correspondente',
            self::OCORRENCIAS_ALEGACOES_CORRESPONDENTE_NAO_SE_INTERESSA_PELO_PROTESTO => 'Correspondente não se interessa pelo protesto',
            self::OCORRENCIAS_ALEGACOES_PAGADOR_NAO_ATENDE_AOS_AVISOS_DE_NOSSOS_CORRESPONDENTES => 'Pagador não atende aos avisos de nossos correspondentes',
            self::OCORRENCIAS_ALEGACOES_TITULO_ESTA_SENDO_ENCAMINHADO_AO_CORRESPONDENTE => 'Titulo está sendo encaminhado ao correspondente',
            self::OCORRENCIAS_ALEGACOES_ENTREGA_FRANCO_DE_PAGAMENTO_AO_PAGADOR => 'Entrega franco de pagamento ao pagador',
            self::OCORRENCIAS_ALEGACOES_ENTREGA_FRANCO_DE_PAGAMENTO_AO_REPRESENTANTE => 'Entrega franco de pagamento ao representante',
            self::OCORRENCIAS_ALEGACOES_A_ENTREGA_FRANCO_DE_PAGAMENTO_E_DIFICIL => 'A entrega franco de pagamento é difícil',
            self::OCORRENCIAS_ALEGACOES_TITULO_RECUSADO_PELO_CARTORIO => 'Titulo recusado pelo cartório',
        );
        return $label[$index];
    }

}
